DROP TABLE IF EXISTS entries;

CREATE TABLE entries (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   number INTEGER NOT NULL,
   datetime TIMESTAMP NOT NULL,
   isExit INTEGER NOT NULL,
   gender TEXT NOT NULL
);
