DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS genders;

CREATE TABLE genders
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE entries (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   number INTEGER NOT NULL,
   datetime TIMESTAMP NOT NULL,
   isExit INTEGER NOT NULL,
   gender INTEGER TEXT NOT NULL,
   FOREIGN KEY (gender)  REFERENCES genders (id)
);
